### ISSUE TITLE
Fix list.append bug. Incorrect method call or use in Person.BasePerson

### ISSUE THREAD

**Issue by Stemist** [pachocanadian/sole#14]
self = <SOLE.Person.BasePerson.BasePerson object at 0x7fba8476f590>
elevator = <SOLE.Elevator.BaseElevator.BaseElevator object at 0x7fba8476f710>

    def load(self, elevator):
        """load() will add person to an elevator."""
    
        # Ask elevator if it is carrying this person; if not then add person.
        if self.get("id") not in elevator.get("carrying"):
>           elevator.set(self.get("carrying"), self.get("carrying").append(self.get(id)))
E           AttributeError: 'NoneType' object has no attribute 'append'

SOLE/Person/BasePerson.py:48: AttributeError

**Comment by pachocanadian** [comment]
There are multiple code problems that I see below. self is a person, first
off, so self.get("carrying") is invalid.

Get returns a reference so I suspect you can do something like

carrying = elevator.get("carrying")
carrying.append(self.id)

Check and see but I suspect it would work fine.

**Comment by pachocanadian** [comment]
Fundamentally you're getting an append error because self.get("carrying") is accessing a non-existent attribute of Person. Because it's non-existent you're getting a None back and you can't use list operators on a None value.

This is not a bug, you are accessing a non-existent attribute and pretending that it should be a list. If you did something like ``elevator.get("carrying").append()`` then that would get you closer to the right idea.

**Comment by Stemist** [comment]
Thanks for outlining the nature of the problems. I'll fix the issues on my next commit tomorrow. Hope things are well in Prince George!

Christian Pearson

christian.pearson@stemist.ca

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
